DROP FUNCTION IF EXISTS get_transformed_moh_515_data(TEXT,TEXT,TEXT,BOOLEAN);
CREATE FUNCTION get_transformed_moh_515_data
(
  param_facility_group_by TEXT,
  param_num_units TEXT DEFAULT '12',
  param_interval_unit TEXT DEFAULT 'months',
  param_include_current BOOLEAN DEFAULT 'false'
)
RETURNS TABLE(
  "dataSet" TEXT,
  "dataElement" TEXT,
  period TEXT,
  "orgUnit" TEXT,
  value NUMERIC
)
AS $BODY$
WITH data_transformation AS (
  SELECT 
    chu_code AS orgUnit,
    period AS period,
    unnest(array[
    'count_new_households_visited_safe_water_new_visit',
    'count_households_hand_washing_facilities_new_visit',
    'count_households_functional_latrines_new_visit',
    'count_newborns_within_48_hours_of_delivery',
    'count_children_12_59_months_dewormed',
    'count_pregnant_women_referred_to_health_facility',
    'count_new_deliveries_at_health_facility',
    'count_children_0_11_months_referred_immunization',
    'count_persons_referred_hts',
    'count_persons_referred_comprehensive_geriatric_services',
    'count_persons_referred_diabetes',
    'count_persons_referred_cancer',
    'count_persons_referred_mental_illness',
    'count_persons_referred_hypertension',
    'count_defaulters_immunization_referred',
    'count_deaths_12_59_months',
    'count_deaths_maternal',
    'count_households_visited_new_visit',
    'count_households_visited_revisit',
    'count_households_new_visit_upto_date_insurance',
    'count_households_new_visit_upto_date_insurance_uhc',
    'count_households_new_visit_upto_date_insurance_nhif',
    'count_households_new_visit_upto_date_insurance_others',
    'count_households_new_visit_refuse_disposal',
    'count_women_15_49_years_counselled_fp',
    'count_women_15_49_years_provided_fp',
    'count_women_15_49_years_referred_fp',
    'count_women_pregnant',
    'count_women_pregnant_underage',
    'count_women_pregnant_counselled_anc',
    'count_new_deliveries',
    'count_new_deliveries_at_home',
    'count_new_deliveries_underage',
    'count_new_mothers_visited_within_48_hours_of_delivery',
    'count_new_deliveries_at_home_referred_pnc',
    'count_children_6_59_months_malnutrition_severe',
    'count_children_6_59_months_malnutrition_moderate',
    'count_children_6_59_months_referred_vitamin_a',
    'count_children_0_59_months_referred_delayed_milestones',
    'count_defaulters_art_referred',
    'count_defaulters_hei_referred',
    'count_defaulters_art_traced_referred',
    'count_defaulters_hei_traced_referred',
    'count_persons_screened_tb',
    'count_persons_presumptive_tb_referred',
    'count_persons_presumptive_tb_referred_confirmed',
    'count_persons_presumptive_tb_referred_confirmed_referred',
    'count_cases_tb_confirmed_0_59_months',
    'count_treatment_interruptors_tb',
    'count_treatment_interrupters_tb_traced',
    'count_women_15_49_years_referred_fp_completed',
    'count_women_pregnant_referred_anc_completed',
    'count_women_referred_pnc_completed',
    'count_defaulters_immunization_referred_completed',
    'count_persons_referred_hts_completed',
    'count_defaulters_art_referred_completed',
    'count_defaulters_hei_referred_completed',
    'count_routine_checkup_referred_completed',
    'count_persons_presumptive_tb_referred_completed',
    'count_persons_presumptive_tb_contacts_referred_completed',
    'count_cases_tb_0_59_months_ipt_referred_completed',
    'count_treatment_interruptors_tb_referred_completed',
    'count_cases_0_59_months_fever_lt_7_days',
    'count_cases_0_59_months_fever_lt_7_days_rdt',
    'count_cases_0_59_months_fever_lt_7_days_rdt_positive',
    'count_cases_0_59_months_fever_lt_7_days_rdt_positive_act',
    'count_cases_2_59_months_fast_breathing',
    'count_cases_2_59_months_fast_breathing_amoxycillin',
    'count_cases_2_59_months_diarrhea',
    'count_cases_2_59_months_diarrhea_zinc_ors',
    'count_cases_gte_60_months_fever_lt_7_days',
    'count_cases_gte_60_months_fever_lt_7_days_rdt',
    'count_cases_gte_60_months_fever_lt_7_days_rdt_positive',
    'count_cases_gte_60_months_fever_lt_7_days_rdt_positive_act',
    'count_deaths_0_28_days',
    'count_deaths_29_days_11_months',
    'count_deaths_6_59_years',
    'count_deaths_gt_60_years',
    'count_households',
    'count_community_dialogue_days',
    'count_community_action_days',
    'count_community_monthly_meetings']
    ) AS echis_name,
    unnest(array[
    count_new_households_visited_safe_water_new_visit,
    count_households_hand_washing_facilities_new_visit,
    count_households_functional_latrines_new_visit,
    count_newborns_within_48_hours_of_delivery,
    count_children_12_59_months_dewormed,
    count_pregnant_women_referred_to_health_facility,
    count_new_deliveries_at_health_facility,
    count_children_0_11_months_referred_immunization,
    count_persons_referred_hts,
    count_persons_referred_comprehensive_geriatric_services,
    count_persons_referred_diabetes,
    count_persons_referred_cancer,
    count_persons_referred_mental_illness,
    count_persons_referred_hypertension,
    count_defaulters_immunization_referred,
    count_deaths_12_59_months,
    count_deaths_maternal,
    count_households_visited_new_visit,
    count_households_visited_revisit,
    count_households_new_visit_upto_date_insurance,
    count_households_new_visit_upto_date_insurance_uhc,
    count_households_new_visit_upto_date_insurance_nhif,
    count_households_new_visit_upto_date_insurance_others,
    count_households_new_visit_refuse_disposal,
    count_women_15_49_years_counselled_fp,
    count_women_15_49_years_provided_fp,
    count_women_15_49_years_referred_fp,
    count_women_pregnant,
    count_women_pregnant_underage,
    count_women_pregnant_counselled_anc,
    count_new_deliveries,
    count_new_deliveries_at_home,
    count_new_deliveries_underage,
    count_new_mothers_visited_within_48_hours_of_delivery,
    count_new_deliveries_at_home_referred_pnc,
    count_children_6_59_months_malnutrition_severe,
    count_children_6_59_months_malnutrition_moderate,
    count_children_6_59_months_referred_vitamin_a,
    count_children_0_59_months_referred_delayed_milestones,
    count_defaulters_art_referred,
    count_defaulters_hei_referred,
    count_defaulters_art_traced_referred,
    count_defaulters_hei_traced_referred,
    count_persons_screened_tb,
    count_persons_presumptive_tb_referred,
    count_persons_presumptive_tb_referred_confirmed,
    count_persons_presumptive_tb_referred_confirmed_referred,
    count_cases_tb_confirmed_0_59_months,
    count_treatment_interruptors_tb,
    count_treatment_interrupters_tb_traced,
    count_women_15_49_years_referred_fp_completed,
    count_women_pregnant_referred_anc_completed,
    count_women_referred_pnc_completed,
    count_defaulters_immunization_referred_completed,
    count_persons_referred_hts_completed,
    count_defaulters_art_referred_completed,
    count_defaulters_hei_referred_completed,
    count_routine_checkup_referred_completed,
    count_persons_presumptive_tb_referred_completed,
    count_persons_presumptive_tb_contacts_referred_completed,
    count_cases_tb_0_59_months_ipt_referred_completed,
    count_treatment_interruptors_tb_referred_completed,
    count_cases_0_59_months_fever_lt_7_days,
    count_cases_0_59_months_fever_lt_7_days_rdt,
    count_cases_0_59_months_fever_lt_7_days_rdt_positive,
    count_cases_0_59_months_fever_lt_7_days_rdt_positive_act,
    count_cases_2_59_months_fast_breathing,
    count_cases_2_59_months_fast_breathing_amoxycillin,
    count_cases_2_59_months_diarrhea,
    count_cases_2_59_months_diarrhea_zinc_ors,
    count_cases_gte_60_months_fever_lt_7_days,
    count_cases_gte_60_months_fever_lt_7_days_rdt,
    count_cases_gte_60_months_fever_lt_7_days_rdt_positive,
    count_cases_gte_60_months_fever_lt_7_days_rdt_positive_act,
    count_deaths_0_28_days,
    count_deaths_29_days_11_months,
    count_deaths_6_59_years,
    count_deaths_gt_60_years,
    count_households,
    count_community_dialogue_days,
    count_community_action_days,
    count_community_monthly_meetings
    ]
    ) AS value
  FROM
  (
    SELECT
      *
    FROM
      get_moh_515_data(param_facility_group_by, param_num_units, param_interval_unit, param_include_current) AS serviceData
      LEFT JOIN (
        SELECT
          chu_uuid AS cu_uuid,
          chu_code AS cu_code,
          period_start AS period_start_date,
          count_community_dialogue_days,
          count_community_action_days,
          count_community_monthly_meetings
        FROM
          get_moh_515_community_events_data(param_facility_group_by, param_num_units, param_interval_unit, param_include_current)
        ) AS eventsData ON (serviceData.chu_uuid=eventsData.cu_uuid AND serviceData.period_start = eventsData.period_start_date)
      ) AS aggregated
)
SELECT
  khis.khis_data_set_uid AS dataSet,
  khis.khis_data_element_uid AS dataElement,
  period,
  orgUnit,
  value
FROM
  data_transformation AS data
  LEFT JOIN echis_khis_data_set_element_mapping AS khis ON khis.echis_name = data.echis_name
$BODY$
LANGUAGE sql STABLE;
