--
-- Name: echis_khis_data_set_element_mapping; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS echis_khis_data_set_element_mapping;
CREATE TABLE echis_khis_data_set_element_mapping (
  id SERIAL PRIMARY KEY NOT NULL,
  khis_data_set_uid VARCHAR(20) NOT NULL,
  khis_data_element_uid VARCHAR(20) NOT NULL,
 	echis_name VARCHAR(100) NOT NULL,
 	description VARCHAR(400) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO echis_khis_data_set_element_mapping(khis_data_set_uid, echis_name, khis_data_element_uid, description)
VALUES
('ovtKPo15xAg', 'count_new_households_visited_safe_water_new_visit', 'OXgWwVp4SLi', 'Total number of NEW households visited in the month accessing safe water (New Visit)'),
('ovtKPo15xAg', 'count_households_hand_washing_facilities_new_visit', 'zhwGF3FDj8B', 'Total number of households with hand washing facilities e.g. leaky tins in use (New visit)'),
('ovtKPo15xAg', 'count_households_functional_latrines_new_visit', 'b16FHzbfVUe', 'Total number of households with functional latrines (New visit)'),
('ovtKPo15xAg', 'count_newborns_within_48_hours_of_delivery', 'NjcDm9nopWu', 'Total number of new-borns visited at home within 48 hours of delivery'),
('ovtKPo15xAg', 'count_children_12_59_months_dewormed', 'vAkP6k0yZDk', 'Total number of children 12-59 months dewormed'),
('ovtKPo15xAg', 'count_pregnant_women_referred_to_health_facility', 'VrpxWLhfIr6', 'Total number of pregnant women Referred  to health facility'),
('ovtKPo15xAg', 'count_new_deliveries_at_health_facility', 'fdsnixQkKCY', 'Total number of New deliveries that took place in Health Facility'),
('ovtKPo15xAg', 'count_children_0_11_months_referred_immunization', 'ZkAL6i7sS2S', 'Total number of mmunization defaulters traced and referred'),
('ovtKPo15xAg', 'count_persons_referred_hts', 'zbYf5G3P7Fv', 'Total number of clients referred for HIV Testing Services (HTS)'),
('ovtKPo15xAg', 'count_persons_referred_comprehensive_geriatric_services', 'hYPcrC46URl', 'Total number of Older persons  (60 years  or more) referred for routine health check ups'),
('ovtKPo15xAg', 'count_persons_referred_diabetes', 'umcBUHyhuTc', 'Total number of persons with Diabetes'),
('ovtKPo15xAg', 'count_persons_referred_cancer', 'SnP5Qr06tLy', 'Total number of persons with cancer'),
('ovtKPo15xAg', 'count_persons_referred_mental_illness', 'd0XSdWwIlCU', 'Total number of persons with Mental Illness'),
('ovtKPo15xAg', 'count_persons_referred_hypertension', 'v9HafndlV8q', 'Total number of persons with Hypertension'),
('ovtKPo15xAg', 'count_defaulters_immunization_referred', 'KHfPfnhSjmA', 'Total number of mmunization defaulters traced and referred'),
('ovtKPo15xAg', 'count_deaths_12_59_months', 'sXPwrF8r04E', 'Record of all deaths between 12 - 59 months of age'),
('ovtKPo15xAg', 'count_deaths_maternal', 'Gx1XLLsvwAZ', 'Record of all deaths of women during pregnancy or child birth or within 42 days after delivery'),
('ovtKPo15xAg', 'count_households_visited_new_visit', 'LGsW5FyZFwZ', 'Total number of households visited by CHVs in the month(New Visit)'),
('ovtKPo15xAg', 'count_households_visited_revisit', 'vGvOtbvhclF', 'Total number of households visited in the month by CHVs(Revisit)'),
('ovtKPo15xAg', 'count_households_new_visit_upto_date_insurance', 'z9qwgod3UiG', 'Total number of households visited in the Month with upto date health insuarance(New Visit)'),
('ovtKPo15xAg', 'count_households_new_visit_upto_date_insurance_uhc', 'd0zEtbkJnel', 'Total number of households visited in the Month with upto date health insuarance-UHC (New Visit)'),
('ovtKPo15xAg', 'count_households_new_visit_upto_date_insurance_nhif', 'xXhZ15pqy4p', 'Total number of households visited in the Month with upto date health insuarance-NHIF (New Visit)'),
('ovtKPo15xAg', 'count_households_new_visit_upto_date_insurance_others', 'KiKtdZ5rV5d', 'Total number of households visited in the Month with upto date health insuarance-OTHERS (New Visit)'),
('ovtKPo15xAg', 'count_households_new_visit_refuse_disposal', 'lhkXObzaWr3', 'Total number of households with Refuse disposal facility (New visit)'),
('ovtKPo15xAg', 'count_women_15_49_years_counselled_fp', 'qNoOzWtEpuD', 'Total number of women (15-49 yrs) counselled on FP methods'),
('ovtKPo15xAg', 'count_women_15_49_years_provided_fp', 'bbrNRV9zwVa', 'Total number of women between 15 - 49 years provided with family planning commodities by CHVs'),
('ovtKPo15xAg', 'count_women_15_49_years_referred_fp', 'TLKNYG2xGad', 'Total Number of women  15-49yrs Referred for   FP Services'),
('ovtKPo15xAg', 'count_women_pregnant', 'NvUUbEhFVcO', 'Total Number of women who are pregnant'),
('ovtKPo15xAg', 'count_women_pregnant_underage', 'h9VcGyaQkfZ', 'Total Number of under-age pregnancies (under 18 years)'),
('ovtKPo15xAg', 'count_women_pregnant_counselled_anc', 'LHd6A9RtHRF', 'Total number of pregnant women counselled on ANC services'),
('ovtKPo15xAg', 'count_new_deliveries', 'jx879BUZ39L', 'Total number of New deliveries that took place in  C.U'),
('ovtKPo15xAg', 'count_new_deliveries_at_home', 'X9d8oaBHDqx', 'Total number of New deliveries that took place at Home'),
('ovtKPo15xAg', 'count_new_deliveries_underage', 'vB85yqSN4gx', 'Total number of New under-age Deliveries (10-19 years) in the month'),
('ovtKPo15xAg', 'count_new_mothers_visited_within_48_hours_of_delivery', 'tuIDKhqDdcB', 'Total number of new mothers visited within 48 hrs of delivery'),
('ovtKPo15xAg', 'count_new_deliveries_at_home_referred_pnc', 'JrdSl1ADdBC', 'Total Home deliveries referred for Post Natal Care (PNC) Services'),
('ovtKPo15xAg', 'count_children_6_59_months_malnutrition_severe', 'idiiaWIh2qi', 'Total number of children (6-59 months) with MUAC (Red) indicating  severe malnutrition'),
('ovtKPo15xAg', 'count_children_6_59_months_malnutrition_moderate', 'ekh0oJidJ38', 'Total number of children (6-59 months) with MUAC (Yellow) indicating  moderate malnutrition'),
('ovtKPo15xAg', 'count_children_6_59_months_referred_vitamin_a', 'ksINuMMr419', 'Total number of children (6-59 months) referred for Vitamin A supplementation'),
('ovtKPo15xAg', 'count_children_0_59_months_referred_delayed_milestones', 'dmU5MIrpsP7', 'Total number of children with delayed milestones referred'),
('ovtKPo15xAg', 'count_defaulters_art_referred', 'TfmOlLMrQc6', 'Total number of ART defaulters in the month (From CCC clinic)'),
('ovtKPo15xAg', 'count_defaulters_hei_referred', 'yHBk3iXClvx', 'Total number of HIV exposed infant defaulters in the month (from MCH)'),
('ovtKPo15xAg', 'count_defaulters_art_traced_referred', 'q90IMsLpFO4', 'Total number of ART defaulters traced and referred'),
('ovtKPo15xAg', 'count_defaulters_hei_traced_referred', 'rdJBPSOGJlA', 'Total number of HIV exposed infant defaulters traced and referred'),
('ovtKPo15xAg', 'count_persons_screened_tb', 'NjCLHbMeaNw', 'Total number of persons screened for TB'),
('ovtKPo15xAg', 'count_persons_presumptive_tb_referred', 'eLMPka37L2p', 'Total number of presumptive TB persons referred for TB diagnosis'),
('ovtKPo15xAg', 'count_persons_presumptive_tb_referred_confirmed', 'HHyDcD7IjqT', 'Total number of bacteriologically confirmed TB cases (From TB clinic)'),
('ovtKPo15xAg', 'count_persons_presumptive_tb_referred_confirmed_referred', 'siQaAwG3fiQ', 'Total number of presumptive TB contacts of bacteriologically confirmed TB cases referred for Screening'),
('ovtKPo15xAg', 'count_cases_tb_confirmed_0_59_months', 'RhriKmKbHuH', 'Total number of children <5 years TB contacts of bacteriologically confirmed TB cases referred for IPT'),
('ovtKPo15xAg', 'count_treatment_interruptors_tb', 'XP1JclLpKdP', 'Total number of TB Treatment Interruptersin the Month (TB clinic)'),
('ovtKPo15xAg', 'count_treatment_interrupters_tb_traced', 'mOoe88OmCct', 'Total number of TB Treatment Interrupters traced'),
('ovtKPo15xAg', 'count_women_15_49_years_referred_fp_completed', 'RivX8a7SDU3', 'Total number of persons referred for FP Services reaching health facility'),
('ovtKPo15xAg', 'count_women_pregnant_referred_anc_completed', 'wYD1JE3Tgsu', 'Total number of pregnabt women reaching health facility'),
('ovtKPo15xAg', 'count_women_referred_pnc_completed', 'vyCCWAqAP5x', 'Total number of mothers referred for post natal services reaching health facility'),
('ovtKPo15xAg', 'count_defaulters_immunization_referred_completed', 'XDgpSRb8Ofv', 'Total number of referred immunization defaulters reaching health facility'),
('ovtKPo15xAg', 'count_persons_referred_hts_completed', 'QAKpLg7iZEJ', 'Total number referred for Hiv testing services reaching health facility'),
('ovtKPo15xAg', 'count_defaulters_art_referred_completed', 'iJpuwr4Hqj1', 'Total number referred ART Defaulters reaching health facility'),
('ovtKPo15xAg', 'count_defaulters_hei_referred_completed', 'r1ed7zn2Q0a', 'Total number referred HIV exposed infant defaulter reaching health facility'),
('ovtKPo15xAg', 'count_routine_checkup_referred_completed', 'ylvw7Y1OB1H', 'Total number referred  for routine check up for older persons reaching health facility'),
('ovtKPo15xAg', 'count_persons_presumptive_tb_referred_completed', 'HC2a1iMVGPv', 'Total number referred presumptive TB casesreaching health facility'),
('ovtKPo15xAg', 'count_persons_presumptive_tb_contacts_referred_completed', 'Qr3F0zbsMmN', 'Total number referred presumptive TB contacts reaching health facility'),
('ovtKPo15xAg', 'count_cases_tb_0_59_months_ipt_referred_completed', 'RlDNgxU0gn3', 'Total number referred  under 5 child Tb contacts for Isoniazid Preventive Therapy reaching health facility'),
('ovtKPo15xAg', 'count_treatment_interruptors_tb_referred_completed', 'RKBTMciF0Tk', 'Total number referred TB INTERRUPTORS reaching health facility'),
('ovtKPo15xAg', 'count_cases_0_59_months_fever_lt_7_days', 'gpYrkLhO4wB', 'Total number of under 5 years cases with fever for less than 7 days'),
('ovtKPo15xAg', 'count_cases_0_59_months_fever_lt_7_days_rdt', 'RXgNfdYSJPh', 'Total number of under 5 years cases with fever for less than 7 days with RDT done'),
('ovtKPo15xAg', 'count_cases_0_59_months_fever_lt_7_days_rdt_positive', 'eUakxWsxkcq', 'Total number of under 5 years cases with fever for less than 7 days with (RDT +ve)  results'),
('ovtKPo15xAg', 'count_cases_0_59_months_fever_lt_7_days_rdt_positive_act', 'V9SqzZHKoP7', 'Total number of under 5 years Malaria Cases (RDT +ve) treated with ACT'),
('ovtKPo15xAg', 'count_cases_2_59_months_fast_breathing', 'WBTvg49kJHr', 'Total number of children aged 2-59 months  presenting with fast breathing'),
('ovtKPo15xAg', 'count_cases_2_59_months_fast_breathing_amoxycillin', 'wMQolZyIR5P', 'Total number of children aged 2-59 months presenting with fast breathing treated with Amoxycillin(DT)'),
('ovtKPo15xAg', 'count_cases_2_59_months_diarrhea', 'V00z4bQRaqe', 'Total number of cases  of diarrhoea identified in children 2-59 months age'),
('ovtKPo15xAg', 'count_cases_2_59_months_diarrhea_zinc_ors', 'AR3WCfcKDwX', 'Total number of children of 2-59 months with diarrhoea treated with Zinc and ORS'),
('ovtKPo15xAg', 'count_cases_gte_60_months_fever_lt_7_days', 'YCWGGPn7tdl', 'Total number of under 5 years cases with fever for less than 7 days'),
('ovtKPo15xAg', 'count_cases_gte_60_months_fever_lt_7_days_rdt', 'ZAsCMIJLkvj', 'Total number of under 5 years cases with fever for less than 7 days with RDT done'),
('ovtKPo15xAg', 'count_cases_gte_60_months_fever_lt_7_days_rdt_positive', 'QfBRPj1q0W1', 'Total number of under 5 years cases with fever for less than 7 days with (RDT +ve)  results'),
('ovtKPo15xAg', 'count_cases_gte_60_months_fever_lt_7_days_rdt_positive_act', 'oVxxa344TPs', 'Total number of under 5 years Malaria Cases (RDT +ve) treated with ACT'),
('ovtKPo15xAg', 'count_deaths_0_28_days', 'bWTVzXQoxpt', 'Record of all deaths between zero to 28 days of age'),
('ovtKPo15xAg', 'count_deaths_29_days_11_months', 'I9yVwu1FWu6', 'Record of all deaths between zero to 11 months of age'),
('ovtKPo15xAg', 'count_deaths_6_59_years', 'jBYvAmDdyfY', 'Record of all deaths 6-59 years(not maternal)'),
('ovtKPo15xAg', 'count_deaths_gt_60_years', 'zW17XEoFhAN', 'Record of all deaths 60 years and above'),
('ovtKPo15xAg', 'count_households', 'rdcZ1ni3jrD', 'Total number of Households'),
('ovtKPo15xAg', 'count_community_dialogue_days', 'Y0ZpWnkp4v9', 'Total number of community dialogue days held'),
('ovtKPo15xAg', 'count_community_action_days', 'ybfaTwL9yBA', 'Total number of community Action Days held'),
('ovtKPo15xAg', 'count_community_monthly_meetings', 'aod6Gz2QUg2', 'Total number of community units monthly meetings held');
